# Generated by Django 5.1 on 2024-09-29 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='zipcode',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
